[connections.supabase]
SUPABASE_URL = "https://kypqmshvizdggmzsyyle.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5cHFtc2h2aXpkZ2dtenN5eWxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4MDU1NjMsImV4cCI6MjA1MTM4MTU2M30.HGWXyx0xAC24OSMpi3_sjMw0eKfe42e3iGw0X1RPLm4"